### ISSUE TITLE
[BUG] The callback isn't called on interact with an item

### ISSUE THREAD

**Issue by ghost** [DayKoala/Windowy#3]
When you set an item with transaction, in certain circustances the callback isn't called, a code example:

```php
$back = ItemFactory::getInstance()->get(ItemIds::BARRIER);
$back->setCustomName("§4§c Back ");

$inventory->setItem(22, $back, function (WindowTransaction $action) {
  // Kit::get() -> Kit (PluginBase)
  Kit::get()
    ->getLogger()
    ->info("Item clicked!");

  $action->cancel();

  $inventory = $action->getInventory();
  $inventory->clearAll();

  // public static function showKitTypes(Window &$window): void
  self::showKitTypes($inventory);
});
```

But, clicking the item don't show anything on console and the cancel action doesn't work

- Platform: Android
- PocketMine-MP Version: 4.2.0
- Minecraft BE Version: 1.18.10
- PHP Version: 8.0

**Comment by DayKoala** [comment]
Sorted out! See the new version available.
